project:
  type: website

website:
  title: "AI & Code"
  site-url: "https://<github‑user>.github.io/ai-code-blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/<github‑user>/ai-code-blog
      - icon: rss
        href: blog.xml
  google-analytics: "G-XXXXXXX"   # TODO: replace with your GA4 measurement ID
  comments:
    giscus:
      repo: "<github‑user>/ai-code-blog"   # enable GitHub Discussions + install Giscus app
      mapping: pathname
      reactions-enabled: true

format:
  html:
    theme: cosmo
    toc: true