project:
  type: website

website:
  title: "Coding with AI"
  site-url: "https://briandw.github.io"
  navbar:
    right:
      - icon: github
        href: https://briandw.github.io
      - icon: rss
        href: blog.xml
  google-analytics: "G-XXXXXXX"   # TODO: replace with your GA4 measurement ID
  comments:
    giscus:
      repo: "briandw/briandw.github.io"   # enable GitHub Discussions + install Giscus app
      mapping: pathname
      reactions-enabled: true

format:
  html:
    include-in-header:
      text: |
        <script defer data-domain="briandw.github.io" src="https://plausible.io/js/script.hash.outbound-links.js"></script>
    theme: cosmo
    toc: true